In [1]:
from urllib.request import urlretrieve
import os
import pandas as pd

# 為了顯示的漂亮, 我刻意的把印出來的 row 只顯示 15 個和 column 只顯示十個
# 大家練習的時候可以去掉下面兩行
pd.set_option('display.max_rows', 15)
pd.set_option('display.max_columns', 10)

data_df = pd.DataFrame(columns = ["content", "sentiment"])

with open("data/study/content_jeiba.txt","r",encoding="utf-8") as fc:
    content = fc.read()
contentList = content.split("\n")


with open("data/study/content_views.txt","r",encoding="utf-8") as fv:
    views = fv.read()
viewsList = views.split("\n")

for line in range(len(viewsList)-1):
    s = pd.Series([contentList[line], viewsList[line]], index = ["content", "sentiment"])
# s = pd.Series([contentList[:len(contentList)-1], viewsList[:len(viewsList)-1]], index = ["content", "sentiment"])
    data_df = data_df.append(s, ignore_index = True)
    
# # 走過 pos 的資料夾，把資料夾整理好
# pos_path = "data/aclImdb/train/pos"
# for fpath in os.listdir(pos_path):
#     if not fpath.startswith("."):
#         fpath = os.path.join(pos_path, fpath)
#         f = open(fpath, "r", encoding = "utf-8")
#         content = f.read()
#         s = pd.Series([content, 1], index = ["content", "sentiment"])
#         train_df = train_df.append(s, ignore_index = True)

# # 走過 neg 的資料夾，把資料夾整理好
# neg_path = "data/aclImdb/train/neg"
# for fpath in os.listdir(neg_path):
#     if not fpath.startswith("."):
#         fpath = os.path.join(neg_path, fpath)
#         f = open(fpath, "r", encoding = "utf-8")
#         content = f.read()
#         s = pd.Series([content, 0], index = ["content", "sentiment"])
#         train_df = train_df.append(s, ignore_index = True)
data_df

content sentiment
0      初三 這天 稱為 「 小年朝 」 ， 也 稱為 「 赤狗日 」 ， 開運 大師 詹惟中 表示...    266947
1      陝西西安 一家 超市 ， 上月 26 日 在 門口 的 一張 告示 引起 網友 熱烈討論 ，...      5828
2      不具名 讀者 問 ：  我家 附近 有 住戶 在 門口 養狗 ， 只要 半夜 經過 狗 都會...      5562
3      日本 連鎖餐廳 正在 拓展 隨選 外送 服務 ， 原因 是 日本政府 調高 消費稅 時將 豁...      4405
4      丹麥 新創公司 ORGANICBASICS 已 發明 穿好 幾周 都 不用 洗的 內褲 ， ...      3843
5      生活市集 觀察 發現 ， 除了 每年 必送 的 養生 補品 禮盒 ， 按摩 相關 商品 也 ...      4108
6      台北國際電玩展 剛風 光 落幕 ， 去年 台灣遊戲 廠 也 有不少 斬獲 ， 在 歷經 多年...     12744
...                                                  ...       ...
15985  沈明 正 ／ 大學 助理 教授  內政部長 針對 酒駕 問題 ， 提出 駕駛人 要 從 「 ...       454
15986  泰國 近日 1 位 女房東 上網 分享 說 ， 她的 公寓 租房 回收 後 ， 內部 都是 ...      8710
15987  16 家 金控 今年 前 2月 獲利 全數 出爐 ， 富邦金 踢走 國泰金 ， 2月 稅後純...      6962
15988  台北市 五分埔 公廁 近來 接 連遭 人 惡意 破壞 ， 警方 調閱 監視器 ， 鎖定 嫌犯...      2370
15989  韓國 天團 「 BIGBANG 」 成員 勝利 醜聞 風暴 越演 越烈 ， 韓媒 《 SBS...     34551
15990  新北市 土 城區 知名 的 「 鼎玉鉉鵝肉店 」 在 2017 年 11 月間 遭人 縱火 ...      3481
15991  2019年 台灣 阿里山櫻花季 已於 3月 9 日至 4月 10 日 正式 開跑 ， 受到 ...        36

[15992 rows x 2 columns]

In [2]:
import math
def trend_log(x):
    x = int(x)
    if abs(x) <= 1:
        return 0
    elif x < 1:
        return math.log10(-1*x) * -1
    else:
        return math.log10(x)

def change48VToClass2(num):
    if num <= 1000:
        return "1000"
    elif num <= 5000:
        return "5000"
    elif num <= 10000:
        return "10000"
    elif num <= 50000:
        return "50000"
    elif num <= 100000:
        return "100k"
    elif num <= 500000:
        return "500k"
    elif num <= 1000000:
        return "1m"
    else:
        return ">1m"

def change48VToClass3(num):
    if num <= 1000:
        return 0
    elif num <= 5000:
        return 1
    elif num <= 10000:
        return 2
    elif num <= 50000:
        return 3
    elif num <= 100000:
        return 4
    elif num <= 500000:
        return 5
    elif num <= 1000000:
        return 6
    else:
        return 7
# y_train.apply(trend_log)

In [3]:
def c_int(x):
    return int(x)
    
data_df["sentiment"] = data_df["sentiment"].apply(c_int)
max_v = max(data_df["sentiment"])
min_v = min(data_df["sentiment"])

In [4]:
def c_v_10(x):
    return ((x-min_v) / (max_v-min_v))
data_df["sentiment"] = data_df["sentiment"].apply(change48VToClass3)

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data_df["content"], data_df["sentiment"], test_size=0.2)

In [6]:
train_df = pd.DataFrame(columns = ["content", "views"])
train_df["content"] = x_train
train_df["views"] = y_train

In [7]:
test_df = pd.DataFrame(columns = ["content", "views"])
test_df["content"] = x_test
test_df["views"] = y_test
test_df

content  views
376    過年 期間 出國度假 ， 不過 卻 遇上 車禍 驚魂 。 可樂旅遊 今 表示 ， 一 北海道...      2
4413   F1 新 年度 賽季 將於 3月 15 日起 ， 於 澳洲墨爾本 登場 ， 法拉利 昨晚 公...      1
4184   對於 彰化 有 民眾 因 照顧 壓力過大 ， 自認 求助 碰壁 ， 老五老基金會 彰化 主任...      2
13035  國民黨中央 今以 土地公生日 為由 ， 邀請 歷任 黨主席 與 副主席 共同 祭拜 ， 在 ...      3
15674  天后 蔡依林 （ JOLIN ） 在 新曲 《 消極 掰 》 MV 中 ， 帶領 大家 一起...      3
1103   華航勞資爭議 在 連日 勞資 駁火 互批 後 演變成 罷工 ， 更 傳出 交部 「 叫 不動...      1
3455   裕隆 （ 2201 ） 自有品牌 納智捷 （ LUXGEN ） 今 舉行 新春 媒體 茶敘 ...      3
...                                                  ...    ...
9289   苗栗縣 25歲 戴姓 孕婦 預產期 在 2月28日 ， 但 她 提早 在 昨天 出現 產兆 ...      1
2761   華航機師罷工 跨 第 6 天 ， 勞資雙方 今 終於 重返 談判桌 第三度 協商 ， 過 上...      2
2524   高雄市 區 鐵路地下化 工程 去年 10 月 完工 通車 ， 高市府 預計 今年 2月 16...      2
11757  今年 動作 不斷的 美巡賽 宣佈 ， 將與 ADOBE 公司 建立 多年 的 市場 合作 夥...      0
11941  藝人 狄鶯 、 孫鵬 愛子 孫安佐 ， 轉型 網紅 ， 近來 他 更是 合體 館長 直播 ，...      5
1236   北市 一名 周姓 廚師 被控 前年 5月 間 趁 餐廳 打烊 後 ， 強脫 獨自 留在 餐廳...      2
1454   年假 每天 晚睡 、 玩 手遊 ， 養成 惰性 ， 當心 開學 、 上班 後 「 回不去 了...      3

[3199 rows x 2 columns]

In [8]:
with open("data/study/feq","r",encoding="utf-8") as fqv:
    feq = fqv.read()
feqList = feq.split("\n")

In [ ]:
from keras.preprocessing.text import Tokenizer
token = Tokenizer(num_words=2000)
token.fit_on_texts(train_df["content"])
# 我省略了這裡的印出，讀者可以把註解秀出字典的樣子
token.word_index

In [9]:
from keras.preprocessing.text import Tokenizer
token = Tokenizer(num_words=2000)
token.fit_on_texts(feqList)
# 我省略了這裡的印出，讀者可以把註解秀出字典的樣子
token.word_index

Using TensorFlow backend.


{'韓國瑜': 1,
 '經濟': 2,
 '川普': 3,
 '民進黨': 4,
 '柯文哲': 5,
 '蔡英文': 6,
 '華航': 7,
 '國民黨': 8,
 '春節': 9,
 '罷工': 10,
 '警察': 11,
 '北京': 12,
 '行政院': 13,
 '營收': 14,
 '機師': 15,
 '香港': 16,
 '習近平': 17,
 '蘇貞昌': 18,
 '北市': 19,
 '北韓': 20,
 '朱立倫': 21,
 '高雄市': 22,
 '台中市': 23,
 '英國': 24,
 '教育部': 25,
 '人民幣': 26,
 '總統大選': 27,
 '吳敦義': 28,
 '新台幣': 29,
 '5g': 30,
 '酒駕': 31,
 '台股': 32,
 '美國': 33,
 '新竹': 34,
 '金正恩': 35,
 '王金平': 36,
 '華為': 37,
 '立委補選': 38,
 '台灣': 39,
 '越南': 40,
 '立法院': 41,
 '中國': 42,
 '台灣燈會': 43,
 '紅包': 44,
 '印度': 45,
 '公投': 46,
 '侯友宜': 47,
 '毒品': 48,
 '貿易戰': 49,
 '農委會': 50,
 '盧秀燕': 51,
 '農民': 52,
 '國道': 53,
 '連假': 54,
 '非洲豬瘟': 55,
 '高雄': 56,
 '醫師': 57,
 '車禍': 58,
 '民調': 59,
 '謝龍介': 60,
 '上海': 61,
 '林佳龍': 62,
 '蘋果': 63,
 '大陸': 64,
 '馬英九': 65,
 '患者': 66,
 '台積電': 67,
 '鄭文燦': 68,
 '南韓': 69,
 '外資': 70,
 '中共': 71,
 '法國': 72,
 '德國': 73,
 '外交部': 74,
 '檢察官': 75,
 '基隆': 76,
 '川金會': 77,
 '經濟部': 78,
 '建築': 79,
 '台大': 80,
 '俄羅斯': 81,
 '金門': 82,
 '澳洲': 83,
 '勞動部': 84,
 '機場': 85,
 '新加坡': 86,
 '手機': 87,
 '委內瑞拉': 8

In [10]:
x_train_seq = token.texts_to_sequences(train_df["content"])
x_test_seq = token.texts_to_sequences(test_df["content"])
pd.DataFrame(x_train_seq)

0       1       2       3       4   ...   884  885  886  887  888
0       276.0  1213.0   952.0  1213.0   952.0 ...   NaN  NaN  NaN  NaN  NaN
1       217.0   558.0  1009.0   217.0   261.0 ...   NaN  NaN  NaN  NaN  NaN
2       193.0   139.0   179.0   193.0   179.0 ...   NaN  NaN  NaN  NaN  NaN
3        20.0   141.0   833.0   367.0    20.0 ...   NaN  NaN  NaN  NaN  NaN
4        44.0    26.0  1541.0    26.0    42.0 ...   NaN  NaN  NaN  NaN  NaN
5        33.0    99.0   649.0  1167.0    98.0 ...   NaN  NaN  NaN  NaN  NaN
6      1422.0  1093.0   194.0    22.0   802.0 ...   NaN  NaN  NaN  NaN  NaN
...       ...     ...     ...     ...     ... ...   ...  ...  ...  ...  ...
12786  1215.0   536.0  1215.0   443.0  1022.0 ...   NaN  NaN  NaN  NaN  NaN
12787  1022.0   802.0   802.0   136.0  1022.0 ...   NaN  NaN  NaN  NaN  NaN
12788   466.0    63.0   498.0   498.0   215.0 ...   NaN  NaN  NaN  NaN  NaN
12789   661.0   513.0   533.0    90.0   670.0 ...   NaN  NaN  NaN  NaN  NaN
12790    42.0   486.0    37.0   144.0   102.0 ...   NaN  NaN  NaN  NaN  NaN
12791  1785.0   278.0   463.0   162.0   162.0 ...   NaN  NaN  NaN  NaN  NaN
12792   719.0  1544.0   316.0  1544.0   316.0 ...   NaN  NaN  NaN  NaN  NaN

[12793 rows x 889 columns]

In [11]:
from keras.preprocessing import sequence
x_train_pad = sequence.pad_sequences(x_train_seq, maxlen = 100)
x_test_pad = sequence.pad_sequences(x_test_seq, maxlen = 100)
pd.DataFrame(x_train_pad)

0   1   2   3   4   ...     95    96    97    98    99
0       0   0   0   0   0  ...   1427  1213    39   691  1090
1       0   0   0   0   0  ...    217   261   217  1343   483
2       0   0   0   0   0  ...   1090    13   248   248   139
3       0   0   0   0   0  ...    371   483   371    63   371
4       0   0   0   0   0  ...     26  1887  1364    26   483
5       0   0   0   0   0  ...     33  1978     3     3   989
6       0   0   0   0   0  ...   1237    56  1090   450    63
...    ..  ..  ..  ..  ..  ...    ...   ...   ...   ...   ...
12786   0   0   0   0   0  ...   1022  1735   483   115  1090
12787   0   0   0   0   0  ...    802   925   990   743     2
12788   0   0   0   0   0  ...    836   611   969   611   611
12789   0   0   0   0   0  ...    661   707   533   691  1090
12790   0   0   0   0   0  ...    371   483   371    63   371
12791   0   0   0   0   0  ...    561   131   374   691  1090
12792   0   0   0   0   0  ...   1090  1213  1213  1213    56

[12793 rows x 100 columns]

In [12]:
x_train_pad[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,  217,  558, 1009,  217,  261,  217, 1343,
        483])

In [13]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.embeddings import Embedding
model = Sequential()
model.add(Embedding(output_dim=32, input_dim=2000, input_length=100))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(units=256, activation='relu'))
model.add(Dropout(0.35))
# 注意一下, 因為我們是二元分類, 最後的激勵函數選擇 sigmoid
# sigmoid(正 + 負 =100%) softmax(類別全部 =100%)
model.add(Dense(units=8, activation='softmax'))

In [14]:
 model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 32)           64000     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100, 32)           0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3200)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               819456    
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 2056      
Total params: 885,512
Trainable params: 885,512
Non-trainable params: 0
_________________________________________________________________


In [15]:
import numpy as np
# 特別注意一下, 因為我們只是二元分類, 所以這裡的 loss 選擇 binary_crossentropy # mean_absolute_error
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
from keras.utils import np_utils
from keras.datasets import imdb
y_train = train_df['views']
y_train_cat = np_utils.to_categorical(y_train)
y_train_cat

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [16]:
train_history = model.fit(x_train_pad, y_train_cat,batch_size = 100, epochs = 3, verbose = 2, validation_split = 0.2)

Train on 10234 samples, validate on 2559 samples
Epoch 1/3
 - 3s - loss: 1.4943 - acc: 0.4234 - val_loss: 1.4099 - val_acc: 0.4529
Epoch 2/3
 - 2s - loss: 1.3175 - acc: 0.4854 - val_loss: 1.3225 - val_acc: 0.4865
Epoch 3/3
 - 2s - loss: 1.1643 - acc: 0.5424 - val_loss: 1.3416 - val_acc: 0.4799


In [17]:
y_test = test_df['views']
y_test_cat = np_utils.to_categorical(y_test)
# 正確率是 list 第二個元素
model.evaluate(x_test_pad, y_test_cat)

3199/3199 [==============================] - 0s 35us/step


[1.351243300414078, 0.4673335416293137]

In [18]:
y_test_cat

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
for i in y_test_cat:
    print(i)

[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0.

[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1.

[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0.

[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0.

[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0.